### ISSUE TITLE
include CamaleonCms::SessionHelper in global scope is unhealthy

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon_oauth#9]
This:

https://github.com/owen2345/camaleon_oauth/blob/master/config/initializers/doorkeeper.rb#L1

makes methods like `current_user` available in the global scope.

However, `current_user` invokes `cama_calc_api_current_user` which invokes `doorkeeper_token`. `doorkeeper_token` is not available in the global scope, hence `current_user` fails.

Furthermore, `cama_current_user` has a cache for the current user value - `@cama_current_user`. This is an instance variable which again is not accessible from the global scope.

Instead of putting methods into the global scope, specific classes or modules should `include CamaleonCms::SessionHelper` etc.

**Comment by owen2345** [comment]
This plugin was not updated since Camaleon_cms 1.x, if you can fix and update I will appreciate.
I think this plugin can be very useful for angularjs integration.
Regards,

**Comment by p-decoraid** [comment]
I am trying to do that, however running into current_user being nil right now. The impression I get is that camaleon-oauth is overwriting some global state set up by camaleon-cms because I am able to check out using a test camaleon-cms installation with camaleon-ecommerce but without camaleon-oauth.

Here is a stack trace:

<pre>
 - draper (2.1.0) lib/draper/helper_proxy.rb:35:in `block in define_proxy'
 - /home/oleg/apps/backend/vendor/cache/camaleon-cms-1d25088e16b3/app/helpers/camaleon_cms/session_helper.rb:144:in `cama_calc_api_current_user'
 - /home/oleg/apps/backend/vendor/cache/camaleon-cms-1d25088e16b3/app/helpers/camaleon_cms/session_helper.rb:110:in `cama_current_user'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/decorators/plugins/ecommerce/product_decorator.rb:108:in `the_qty_real'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/decorators/plugins/ecommerce/product_item_decorator.rb:34:in `decrement_qty!'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/models/plugins/ecommerce/cart.rb:82:in `block in make_order!'
 - draper (2.1.0) lib/draper/delegation.rb:10:in `each'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/models/plugins/ecommerce/cart.rb:82:in `make_order!'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/models/plugins/ecommerce/cart.rb:148:in `make_paid!'
 - draper (2.1.0) lib/draper/delegation.rb:10:in `make_paid!'
 - draper (2.1.0) lib/draper/automatic_delegation.rb:10:in `method_missing'
 - /home/oleg/apps/backend/vendor/cache/camaleon-ecommerce-a8543f617be2/app/helpers/plugins/ecommerce/ecommerce_email_helper.rb:5:in `mark_order_like_received'
</pre>

How is mark_order_like_received/make_paid!/make_order! intended to make current_user work?

Here is something else related. `prod` is a Product instance in this mark_order_like_received etc. process:

<pre>
(byebug) prod.current_user
#<CamaleonCms::UserDecorator:0x007f5700914458 @object=#<CamaleonCms::User id: 1, username: "admin", role: "admin", email: "admin@local.com", slug: nil, password_digest: "$2a$10$/HuEU3MBQGBBNV.MJiNQJOdj5gbigcx0x.G1GjdUCdV...", auth_token: "oRsdIJH21JoElcTO67H4JQ", password_reset_token: nil, parent_id: nil, password_reset_sent_at: nil, last_login_at: "2016-08-29 21:26:45", created_at: "2016-08-29 21:26:29", updated_at: "2016-08-29 21:26:45", site_id: -1, confirm_email_token: nil, confirm_email_sent_at: nil, is_valid_email: true, first_name: "Administrator", last_name: nil>, @context={}>
(byebug) prod.cama_current_user
*** NoMethodError Exception: undefined method `cama_current_user' for #<Plugins::Ecommerce::ProductDecorator:0x007f5704754f60>
nil
</pre>

Where is the current_user method defined that ends up being on the product instance?
